### ISSUE TITLE
How to disable braintree on self-host version

### ISSUE THREAD

**Issue by peaceooout** [cablej/FileChangeMonitor#1]
Hi,

I want to deploy this program on my own server but keep showing the error Missing PublicKey for braintree.Do you know how to disable the braintreepayment on self-host version?

Thanks!

**Comment by cablej** [comment]
Hi @pnigos,

I pushed a change to support this. Add the following to your `.env` file after pulling from master:

```
PAYMENT_TYPE=sandbox
FREE_FILE_LIMIT=1000
```

Please let me know if you run into any more issues.

Jack

**Comment by peaceooout** [comment]
Thanks you!
